- name: Install Flatpaks
  become: false
  block:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install multiple packages
      community.general.flatpak:
        name: "{{ flatpak_apps }}"
        remote: "flathub"
        method: "user"