# Install Nerd font
- name: Install Jetbrains Nerd Font
  block:
    - name: Create Directory
      ansible.builtin.file:
        path: "{{ font_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
    - name: Download
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
        dest: "{{ font_dir }}"
        remote_src: true
        owner: "{{ user }}"
        group: "{{ user }}"
    - name: Font cache update
      ansible.builtin.command: fc-cache -fv
      register: cmd_result # <- Registers the command output.
      changed_when: my_cmd_result.rc != 0 # <- Uses the return code to define when the task has changed.
      when: ansible_system |lower == "linux"
      
