# Install Nerd font
- name: Install Jetbrains Nerd Font
  block:
    - name: Create Directory
      ansible.builtin.file:
        path: "{{ fonts_dir }}/JetBrainsMonoNerd"
        state: directory
        mode: "0755"
    - name: Download
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
        dest: "{{ fonts_dir }}/JetBrainsMonoNerd"
        remote_src: true
    - name: Font cache update
      ansible.builtin.command: fc-cache -fv
      register: cmd_result
      changed_when: cmd_result.rc != 0

