- name: Install docker
  dnf:
    name:
      - docker
      - docker-compose
    state: latest
  become: true

- name: Create docker group
  group:
    name: docker
    state: present
    system: true
  become: true

- name: Append the user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true