- name: Install packages
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - add_repo.yml
    - lazygit.yml
    - install.yml
    - docker.yml
    - mise.yml
    - starship.yml
    - rustup.yml
