- name: Enable Starship copr
  become: true
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: atim/starship
- name: Install Starship
  become: true
  ansible.builtin.dnf:
    name: starship
    state: present
