- name: Get chezmoi install
  get_url:
    url: https://get.chezmoi.io
    dest: /tmp/chezmoi
    mode: '0755'
- name: Initialize Chezmoi
  ansible.builtin.shell: "/tmp/chezmoi init --apply rxx"
  args:
    executable: /bin/bash
    chdir: "{{ home_dir }}"