- name: Setup dev machine
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - role: common
    - role: fonts
    - role: dotfiles
    - role: fedora
      when: ansible_distribution | lower == "fedora"
    - role: macos
      when: ansible_system | lower == "darwin"
