- name: Set fish shell default
  ansible.builtin.shell: chsh -s $(which fish)
  args:
    executable: /bin/fish

- name: Install Linux Brew
- name: Install
  when: not starship.stat.exists
  ansible.builtin.shell: "{{ linuxbrew_executable }} install starship"
  args:
    executable: /bin/fish
    
- name: Check for Google Chrome repo
  stat: path=/etc/yum.repos.d/google-chrome.repo
  register: chrome_installed

- name: Install Google Chrome repo
  dnf:
    name: 'https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'
    state: present
  when: not chrome_installed.stat.exists
      
- name: Check for vscode repo
  stat: path=/etc/yum.repos.d/vscode.repo
  register: fedora_vscode_installed
      
- name: Check for RPM Fusion Free repo
  stat: path=/etc/yum.repos.d/rpmfusion-free.repo
  register: fedora_rpm_fusion_free_installed

- name: Check for RPM Fusion Nonfree repo
  stat: path=/etc/yum.repos.d/rpmfusion-nonfree.repo
  register: fedora_rpm_fusion_nonfree_installed
  
# when: not fedora_rpm_fusion_free_installed.stat.exists

- name: Set fs.inotify.max_user_watches to 524288
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    sysctl_set: yes
    state: present
    reload: yes
    
- name: Create Vagrant group
  group:
    name: vagrant
    state: present
    
- name: Setup {{ local_user }} user
  user:
    name: "{{ local_user }}"
    home: /home/{{ local_user }}
    groups: mock,vagrant,libvirt,wheel
    append: yes

- name: Allow wheel group to sudo without a password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  when: local_user_passwordless_

- Configure tools:
    - neovim - add min config
    - Configure kitty
    - Learn kitty commands
    - Configure starship
    - Install rust, python, node, ruby local
    - Add fish plugins