home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
fonts_dir: "{{ home_dir }}/.local/share/fonts"
user: "{{ lookup('ansible.builtin.env', 'USER') }}"
bin_dir: "{{ home_dir }}/bin"

package_apps:
  # Terminal Tools
  - git
  - fish
  - zsh
  - kitty
  - bat
  - fzf
  - zoxide
  - lsd
  - sd
  - procs
  - curl
  - code
  - python
  - wl-clipboard
  - ripgrep
  - ShellCheck
  # Apps
  - krusader
  - ranger
  - keepassxc
  - firefox
  # Ruby Deps
  - libffi-devel
  - autoconf
  - automake
  - gcc-c++
  - libtool
  - libyaml-devel
  - readline-devel
  - sqlite-devel

flatpak_apps:
  - com.discordapp.Discord
  - org.telegram.desktop
  - us.zoom.Zoom
  - com.logseq.Logseq
  - md.obsidian.Obsidian
