home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
fonts_dir: "{{ home_dir }}/.local/share/fonts"

package_apps:
  - git
  - fish
  # - starship
  - bat
  - fzf
  - zoxide
  - lsd
  - sd
  - procs
  # - krusander
  - ranger
  - python
  - curl

flatpack_apps:
  - com.google.Chrome
  - com.visualstudio.code
  - org.videolan.VLC
  - com.discordapp.Discord
  - org.telegram.desktop
  - com.github.tchx84.Flatseal
  - us.zoom.Zoom