home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
fonts_dir: "{{ home_dir }}/.local/share/fonts"

package_apps:
  # Terminal Tools
  - git
  - fish
  # - starship
  - kitty
  - bat
  - fzf
  - zoxide
  - lsd
  - sd
  - procs
  - curl
  - python
  - wl-clipboard
  # Apps
  - krusader
  - ranger
  - keepassxc
  - neovim

flatpak_apps:
  - com.google.Chrome
  - com.visualstudio.code
  - com.discordapp.Discord
  - org.telegram.desktop
  - us.zoom.Zoom
